---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: csi-driver-nfs
resources:
- namespace.yaml
- repo.yaml
- chart.yaml
- release.yaml
- local-storage-class-v2.yaml
- remote-storage-class.yaml
- debian-storage-class.yaml
- local-storage-class-next.yaml
