---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuthGlobal
metadata:
  name: default
spec:
  allowedNamespaces:
  - reflector
  - gluetun-proxy
  defaultAuthMethod: kubernetes
  kubernetes:
    audiences:
    - vault
    mount: kubernetes
    role: global-vault-auth
    serviceAccount: vault-secrets-operator-vault-serviceaccount
    tokenExpirationSeconds: 600
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets-operator-vault-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-token-reviewer
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-secrets-operator-vault-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-token-reviewer
subjects:
- kind: ServiceAccount
  name: vault-secrets-operator-vault-serviceaccount
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: default
spec:
  address: http://vault-ui.vault.svc.cluster.local:8200
