---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: netbird
    app.kubernetes.io/version: latest
  name: netbird
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: netbird
  template:
    metadata:
      labels:
        app.kubernetes.io/name: netbird
        app.kubernetes.io/version: latest
    spec:
      containers:
      - image: netbirdio/netbird:latest
        name: netbird
        env:
        - name: NB_SETUP_KEY
          valueFrom:
            secretKeyRef:
              key: setup-key
              name: netbird-setup-key-vault-secret
        - name: NB_HOSTNAME
          value: netbird-k8s-router
        - name: NB_LOG_LEVEL
          value: debug
        - name: ENABLE_ROSENPASS
          value: "true"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_RESOURCE
            - SYS_ADMIN
