---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jellyfin
resources:
- namespace.yaml
- repo.yaml
- chart.yaml
- release.yaml
- pvc.yaml
- scaled-object.yaml
- network-policy.yaml
