---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: elastic-stack
resources:
- namespace.yaml
- repo.yaml
- chart.yaml
- release.yaml
- vector-role.yaml
- service.yaml
