---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: booklore
    app.kubernetes.io/version: " v1.15.0"
  name: booklore
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: booklore
  template:
    metadata:
      labels:
        app.kubernetes.io/name: booklore
        app.kubernetes.io/version: " v1.15.0"
    spec:
      containers:
      - image: "booklore/booklore: v1.15.0"
        name: booklore
        ports:
        - containerPort: 6060
          name: booklore
        volumeMounts:
        - mountPath: /app/data
          name: data-volume
        - mountPath: /books
          name: books-volume
        - mountPath: /bookdrop
          name: bookdrop-volume
        env:
        - name: USER_ID
          value: "0"
        - name: GROUP_ID
          value: "0"
        - name: TZ
          value: Europe/Vienna
        - name: DATABASE_URL
          value: jdbc:mariadb://mariadb.mariadb.svc.cluster.local:3306/booklore
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mariadb-creds-secret
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: mariadb-creds-secret
        - name: BOOKLORE_PORT
          value: "6060"
        - name: SWAGGER_ENABLED
          value: "false"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: books-volume
        persistentVolumeClaim:
          claimName: books-pvc
      - name: bookdrop-volume
        persistentVolumeClaim:
          claimName: bookdroppvc-pvc
