---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: redlib
    app.kubernetes.io/version: sha-ba98178
  name: redlib
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redlib
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redlib
        app.kubernetes.io/version: sha-ba98178
    spec:
      containers:
      - image: quay.io/redlib/redlib:sha-ba98178
        name: redlib
        ports:
        - containerPort: 8080
          name: redlib
