---
apiVersion: v1
kind: Service
metadata:
  annotations:
    netbird.io/expose: "true"
    netbird.io/groups: cluster-services
  labels:
    app.kubernetes.io/name: redlib
    app.kubernetes.io/version: sha-ba98178
  name: redlib
spec:
  selector:
    app.kubernetes.io/name: redlib
  ports:
  - name: http-redlib
    port: 8080
    targetport: 8080
