---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: netbird-operator-config-repo
spec:
  type: default
  url: https://netbirdio.github.io/kubernetes-operator
  interval: 24h
