data_dir: "/var/lib/vector"
api:
  enabled: false
sources:
  k8s_in:
    type: "kubernetes_logs"
sinks:
  es_cluster:
    inputs:
      - "k8s_in"
    type: "elasticsearch"
    endpoints:
      - "http://elasticsearch-es-internal-http.elastic-stack.svc.cluster.local:9200"
    bulk:
      index: "vector-%Y-%m-%d" # daily indices
