---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: localai
    app.kubernetes.io/version: localai:v3.9.0-aio-cpu
  name: localai
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: localai
  template:
    metadata:
      labels:
        app.kubernetes.io/name: localai
        app.kubernetes.io/version: localai:v3.9.0-aio-cpu
    spec:
      containers:
      - image: quay.io/go-skynet/local-ai:localai:v3.9.0-aio-cpu
        name: localai
        ports:
        - containerPort: 8080
          name: localai
        volumeMounts:
        - mountPath: /models
          name: model-volume
        - mountPath: /tmp/generated
          name: output-volume
        - mountPath: /dev/dri
          name: dri
          readonly: true
        - mountPath: /backends
          name: backends-volume
        env:
        - name: DEBUG
          value: "true"
        resources:
          limits:
            gpu.intel.com/i915: "1"
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc
      - name: output-volume
        persistentVolumeClaim:
          claimName: output-pvc
      - name: dri
        hostPath:
          path: /dev/dri
          type: Directory
      - name: backends-volume
        persistentVolumeClaim:
          claimName: backends-pvc
