---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: localai
    app.kubernetes.io/version: v3.9.0-aio-cpu
  name: localai
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: localai
  template:
    metadata:
      labels:
        app.kubernetes.io/name: localai
        app.kubernetes.io/version: v3.9.0-aio-cpu
    spec:
      runtimeClassName: nvidia
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: exclusive
                operator: In
                values:
                - localai
      containers:
      - image: quay.io/go-skynet/local-ai:v3.9.0-aio-cpu
        name: localai
        ports:
        - containerPort: 8080
          name: localai
        volumeMounts:
        - mountPath: /models
          name: model-volume
        - mountPath: /tmp/generated
          name: output-volume
        - mountPath: /backends
          name: backends-volume
        env:
        - name: DEBUG
          value: "true"
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc
      - name: output-volume
        persistentVolumeClaim:
          claimName: output-pvc
      - name: backends-volume
        persistentVolumeClaim:
          claimName: backends-pvc
      tolerations:
      - key: exclusive
        operator: Equal
        value: localai
        effect: NoSchedule
