---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: localai
resources:
- namespace.yaml
- model-pvc.yaml
- output-pvc.yaml
- backends-pvc.yaml
- deployment.yaml
- service.yaml
- scaled-object.yaml
