---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: localai
    app.kubernetes.io/version: master-gpu-nvidia-cuda-12
  name: localai
spec:
  selector:
    app.kubernetes.io/name: localai
  ports:
  - name: http-localai
    port: 8080
    targetPort: 8080
