---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: transmission
resources:
- deployment.yaml
- vault-secret.yaml
- service.yaml
- trans-pvc.yaml
- trans-config-pvc.yaml
- flood-config-pvc.yaml
- configmap.yaml
