---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: transsetup
    app.kubernetes.io/version: "1.0"
  name: transmission
spec:
  selector:
    app.kubernetes.io/name: transsetup
    app.kubernetes.io/version: "1.0"
  ports:
  - name: http-trans-webui
    port: 9091
    targetPort: 9091
