---
apiVersion: v1
kind: Service
metadata:
  annotations:
    netbird.io/expose: "true"
    netbird.io/groups: cluster-services
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/version: sha-6f9fab1
  name: synapse
spec:
  selector:
    app.kubernetes.io/name: synapse
  ports:
  - name: http-synapse
    port: 8008
    targetport: 8008
