---
apiVersion: v1
kind: Service
metadata:
  annotations:
    netbird.io/expose: "true"
    netbird.io/groups: cluster-services
  labels:
    app.kubernetes.io/name: mealie
    app.kubernetes.io/version: v3.0.2
  name: mealie
spec:
  selector:
    app.kubernetes.io/name: mealie
  ports:
  - name: http-mealie
    port: 9000
    targetport: 9000
