services:
  # Zitadel - identity provider
  zitadel:
    restart: "always"
    networks: [zitadel, netbird, caddy]
    image: "ghcr.io/zitadel/zitadel:v4.3.0"
    command: "start-from-init --masterkeyFromEnv --tlsMode external"
    env_file:
      - ./zitadel.env
    depends_on:
      zdb:
        condition: "service_healthy"
    volumes:
      - ./machinekey:/machinekey
      - netbird_zitadel_certs:/zdb-certs:ro
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
  # Postgres for Zitadel
  zdb:
    restart: "always"
    networks: [zitadel]
    image: "postgres:16-alpine"
    env_file:
      - ./zdb.env
    volumes:
      - netbird_zdb_data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 60s
      retries: 10
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
volumes:
  netbird_zdb_data:
  netbird_zitadel_certs:
