---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: piped-backend
    app.kubernetes.io/version: ""
  name: piped-backend
spec:
  selector:
    app.kubernetes.io/instance: piped
    app.kubernetes.io/name: piped-frontend
  ports:
  - name: http-piped-backend
    port: 8080
    targetPort: 8080
