---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: flood
    app.kubernetes.io/version: "1.0"
  name: flood
spec:
  selector:
    app.kubernetes.io/name: flood
    app.kubernetes.io/version: "1.0"
  ports:
  - name: http-flood-webui
    port: 3000
    targetPort: 3000
