---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: discord-bridge
    app.kubernetes.io/version: v0.7.5
  name: discord-bridge
spec:
  selector:
    app.kubernetes.io/name: discord-bridge
  ports:
  - name: http-discord-bridge
    port: 29334
    targetPort: 29334
