---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: stash
    app.kubernetes.io/version: v0.30.0
  name: stash
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stash
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stash
        app.kubernetes.io/version: v0.30.0
    spec:
      containers:
      - image: stashapp/stash:v0.30.0
        name: stash
        ports:
        - containerPort: 9999
          name: stash
        volumeMounts:
        - mountPath: /root/.stash
          subPath: config
          name: volume
        - mountPath: /data
          subPath: data
          name: volume
        - mountPath: /metadata
          subPath: metadata
          name: volume
        - mountPath: /blobs
          subPath: blobs
          name: volume
        - mountPath: /generated
          subPath: generated
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: stash-pvc
