---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: stash
    app.kubernetes.io/version: v0.30.0
  name: stash
spec:
  selector:
    app.kubernetes.io/name: stash
  ports:
  - name: http-stash
    port: 9999
    targetPort: 9999
