services:
  caddy:
    build:
      context: ./
      target: caddy
    env_file:
      - "../crowdsec.env"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - caddy-logs:/var/log/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks: [caddy, crowdsec, netbird, zitadel, keycloak]
    security_opt:
      - no-new-privileges=true
