---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: piped
    app.kubernetes.io/version: ""
  name: piped
spec:
  selector:
    app.kubernetes.io/instance: piped
    app.kubernetes.io/name: piped-frontend
  ports:
  - name: http-piped
    port: 80
    targetPort: 80
