---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: affine
    app.kubernetes.io/version: 2026.1.11-canary.904
  name: affine
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: affine
  template:
    metadata:
      labels:
        app.kubernetes.io/name: affine
        app.kubernetes.io/version: 2026.1.11-canary.904
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - /scripts/entrypoint.sh
        image: ghcr.io/toeverything/affine:2026.1.11-canary.904
        name: affine
        ports:
        - containerPort: 3010
          name: affine-ui
        volumeMounts:
        - mountPath: /root/.affine/config
          name: conf-volume
        - mountPath: /root/.affine/storage
          name: data-volume
        - mountPath: /scripts/entrypoint.sh
          subPath: entrypoint.sh
          name: entrypoint-volume
        env:
        - name: REDIS_SERVER_HOST
          value: redis.redis.svc.cluster.local
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: affine-pg-creds-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: affine-pg-creds-secret
        - name: DB_DATABASE
          value: affine-db
      volumes:
      - name: conf-volume
        persistentVolumeClaim:
          claimName: config-pvc
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: entrypoint-volume
        configMap:
          name: affine-configmap
          defaultMode: 511
