---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nvidia-k8s-device-plugin
resources:
- namespace.yaml
- repo.yaml
- chart.yaml
- release.yaml
- network-policy.yaml
