---
apiVersion: v1
kind: ConfigMap
metadata:
  name: audiomuse-configmap
data:
  CLAP_ENABLED: "true"
  JELLYFIN_URL: http://jellyfin.jellyfin.svc.cluster.local
  MEDIASERVER_TYPE: jellyfin
  POSTGRES_DB: audiomuseai
  POSTGRES_HOST: postgres-rw.postgres.svc.cluster.local
  POSTGRES_PORT: "5432"
  REDIS_URL: redis://redis.redis.svc.cluster.local:6379/0
  TEMP_DIR: /app/temp_audio
