---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: audiomuse-ai
resources:
- flask-deployment.yaml
- worker-deployment.yaml
- service.yaml
- configmap.yaml
- vault-secret.yaml
- pvc.yaml
