---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: audiomuse-ai
    app.kubernetes.io/version: 0.8.6
  name: audiomuse-ai
spec:
  selector:
    app.kubernetes.io/name: audiomuse-ai-flask
    app.kubernetes.io/version: 0.8.6
  ports:
  - name: http-audiomuse
    port: 8000
    targetPort: 8000
