---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: audiomuse-ai-worker
    app.kubernetes.io/version: 0.8.6
  name: audiomuse-ai-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: audiomuse-ai-worker
      app.kubernetes.io/version: 0.8.6
  template:
    metadata:
      labels:
        app.kubernetes.io/name: audiomuse-ai-worker
        app.kubernetes.io/version: 0.8.6
    spec:
      containers:
      - image: ghcr.io/neptunehub/audiomuse-ai:0.8.6
        name: audiomuse-ai-worker
        ports:
        - containerPort: 8000
          name: worker
        env:
        - name: SERVICE_TYPE
          value: worker
        - name: JELLYFIN_USER_ID
          valueFrom:
            secretKeyRef:
              key: userid
              name: jellyfin-creds
        - name: JELLYFIN_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: jellyfin-creds
        - name: POSTGRES_USER
          value: worker
        - name: POSTGRES_PASSWORD
          value: worker
        envFrom:
        - configMapRef:
            name: audiomuse-configmap
