---
apiVersion: v1
kind: ConfigMap
metadata:
  name: invidious-cm
data:
  config.yaml: |
    db:
      dbname: invidious
      user: ${PG_USER}
      password: ${PG_PASSWORD}
      host: postgres-rw.postgres.svc.cluster.local
      port: 5432
    check_tables: true
    invidious_companion:
      - private_url: "http://localhost:8282/companion"
    invidious_companion_key: "${COMPANION_KEY}"
    hmac_key: "${HMAC_KEY}"
