---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: invidious
resources:
- namespace.yaml
- service.yaml
- cache-pvc.yaml
- deployment.yaml
- configmap.yaml
- config-pvc.yaml
