---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: whatsapp-bridge
resources:
- namespace.yaml
- deployment.yaml
- data-pvc.yaml
- service.yaml
- configmap.yaml
- network-policy.yaml
