---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: whatsapp-bridge
    app.kubernetes.io/version: v25.12
  name: whatsapp-bridge
spec:
  selector:
    app.kubernetes.io/name: whatsapp-bridge
  ports:
  - name: http-whatsapp-bridge
    port: 29318
    targetPort: 29318
