include:
  - caddy/docker-compose.yaml
  - zitadel/docker-compose.yaml
  - netbird/docker-compose.yaml
  - keycloak/docker-compose.yaml
  - crowdsec/docker-compose.yaml
  - crowdsec-ui/docker-compose.yaml
networks:
  caddy:
  netbird:
  keycloak:
  crowdsec:
    driver: bridge
  zitadel:
volumes:
  caddy-logs:
  caddy-data:
  caddy-config:
