---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jellyfin
resources:
- namespace.yaml
- repo.yaml
- chart.yaml
- release.yaml
- pvc.yaml
- deployment.yaml
- scaled-object.yaml
- quic-config-pvc.yaml
- qbit-config-pvc.yaml
- vault-secret.yaml
- service.yaml
