---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: qbitsetup
    app.kubernetes.io/version: "1.0"
  name: qbit
spec:
  selector:
    app.kubernetes.io/name: qbitsetup
    app.kubernetes.io/version: "1.0"
  ports:
  - name: http-qbit-webui
    port: 8080
    targetPort: 8080
