---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: caddy
    app.kubernetes.io/version: latest
  name: caddy
spec:
  selector:
    app.kubernetes.io/name: caddy
  ports:
  - name: http-caddy
    port: 80
    targetport: 80
