---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 11.4.5
  name: mariadb
spec:
  selector:
    app.kubernetes.io/name: mariadb
  ports:
  - name: tcp-mariadb
    port: 3306
    targetPort: 3306
