---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: lidify
    app.kubernetes.io/version: v1.0.2
  name: lidify
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lidify
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lidify
        app.kubernetes.io/version: v1.0.2
    spec:
      containers:
      - image: chevron7locked/lidify:v1.0.2
        name: lidify
        ports:
        - containerPort: 3030
          name: lidify
        volumeMounts:
        - mountPath: /music
          name: music-volume
        - mountPath: /data
          name: config-volume
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: lidify-config-pvc
      - name: music-volume
        persistentVolumeClaim:
          claimName: lidify-music-pvc
      nodeSelector:
        kubernetes.io/hostname: debian
