---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: lidify
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- config-pvc.yaml
- music-pvc.yaml
- scaled-object.yaml
