---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: piped-ytproxy
    app.kubernetes.io/version: ""
  name: piped-ytproxy
spec:
  selector:
    app.kubernetes.io/instance: piped
    app.kubernetes.io/name: piped-frontend
  ports:
  - name: http-piped-ytproxy
    port: 8080
    targetPort: 8080
